lib/MetaCPAN/Document/File.pm, t/document/file.t
A fix for #358, not ready to merge.
=> Packages with leading underscores not indexed

.perlcriticrc
I find the benefits of these policies to be arguable and negligible.
I spend more time making perlcritic happy than they provide for
readability or avoiding bugs.  If someone really finds `','` and `''`
hard to read we can turn them back on.
ProhibitInterpolationOfLiterals requires a special note because its
rationales are wrong.  Interpolated strings are compiled to literals
with concatenation and the compile time saved is wholly negligible
(especially for a project using Moose).
The policy cannot know if `'Foo $bar'` was intentional or not so the
rationale of communicating intent doesn't work.  On the other side,
strict will catch if `"Foo $bar"` is a mistake, but cannot catch if 
`'Foo $bar'` is a mistake and neither can be policy.
=> Turn off some PBP policies that aren't very helpful.

cpanfile, cpanfile.snapshot, lib/MetaCPAN/Document/File.pm, t/document/file.t
This is a new pull request for #110 because I cleaned my commit history and rebased and somehow the pull request got closed automatically. This commit is ready for review.
=> Files listed under other files are not authorized

lib/MetaCPAN/Document/File.pm, lib/MetaCPAN/Model/Release.pm, t/release/common-files.t, t/var/fakecpan/configs/common-files.yml
#385 set "indexed: false" for common release files (things that are not modules).
It had passing unit tests, however the code was actually not getting called during indexing:
* `set_indexed` is only called for module files
* the default was being set by `meta->should_index_file` before the object was created.
This adds an integration test and moves the "default" logic into a lazy builder where I think it makes the most sense.
Any thoughts?
=> Actually use "indexed:false" logic for common files

lib/MetaCPAN/Document/Release.pm, lib/MetaCPAN/Model/Release.pm, t/release/file-changes.t, t/release/perl-changes-file.t, t/release/pod-examples.t, t/var/fakecpan/configs/pod-examples.json
This is a fix for #299 and it is ready for review.
=> add changes_file field (adds new mappings)

docs/API-docs.md
The MetaCPAN Explorer currently doesn't work in Firefox with http://
Firefox blocks requests to http://api.metacpan.org as it is Cross-Origin. But they work in https://.
This is probably fixable server side (the Firefox console says to enable CORS), but in the mean time, just fix the links from the doc.
=> API-docs.md: fix all Explorer links to use https

lib/MetaCPAN/Pod/XHTML.pm, lib/MetaCPAN/Server/Controller/Source.pm, lib/MetaCPAN/Server/View/Pod.pm
For files inside the same dist, improve the links generated in the pod.  For files that aren't modules, use /pod/distribution/$dist/$file.  For unauthorized modules or when the permalinks request parameter is used, use /pod/release/$author/$release/$file.
This does not yet address when multiple files have the same pod name.
=> Improve pod links to files in the same dist

lib/MetaCPAN/Document/File.pm, t/document/file.t
The list of files given as 'other' are meant to be excluded from
indexing in the root of a dist.  Some may intentionally exist in
subdirectories (particularly in lib/) and meant to be indexed.  Instead
of matching based on the filename, match based on the full path so it
only applies to files in the root directory (so far).
Fixes CPAN-API/metacpan-web#1576
=> match 'other files' by path, not filename

lib/MetaCPAN/Script/Release.pm
As otherwise Perl6 namespaces can clash with Perl5 ones and cause oddities
=> Do not index anything in a /Perl6/ directory

cpanfile.snapshot, lib/Catalyst/Plugin/OAuth2/Provider.pm, lib/Catalyst/Plugin/Session/Store/ElasticSearch.pm, lib/MetaCPAN/Document/Author.pm, lib/MetaCPAN/Document/Distribution.pm, lib/MetaCPAN/Document/File.pm, lib/MetaCPAN/Document/Module.pm, lib/MetaCPAN/Document/Rating.pm, lib/MetaCPAN/Document/Release.pm, lib/MetaCPAN/Model/Archive.pm, lib/MetaCPAN/Model/Release.pm, lib/MetaCPAN/Model/User/Account.pm, lib/MetaCPAN/Pod/Renderer.pm, lib/MetaCPAN/Role/Fastly.pm, lib/MetaCPAN/Role/Logger.pm, lib/MetaCPAN/Script/Author.pm, lib/MetaCPAN/Script/Check.pm, lib/MetaCPAN/Script/First.pm, lib/MetaCPAN/Script/Latest.pm, lib/MetaCPAN/Script/Release.pm, lib/MetaCPAN/Script/Tickets.pm, lib/MetaCPAN/Server/Controller/Login/OpenID.pm, lib/MetaCPAN/Server/Controller/User/Turing.pm, lib/MetaCPAN/Server/Diff.pm, lib/MetaCPAN/Server/User.pm, lib/MetaCPAN/Types/Internal.pm, t/lib/MetaCPAN/Tests/Model.pm
Just removing some direct imports we already have through `MetaCPAN::Types`.
This is still open because:
The one I couldn't remove was uses of `MooseX::Types::Structured` since it's not playing nicely with `MooseX::Types::Combine` - we should probably report this or find a workaround, for now having it in the list of `provide_types_from` seems meaningless.
Any thoughts on this?
=> WIP: cleaning up types usage

.gitignore, lib/MetaCPAN/Document/Distribution.pm, lib/MetaCPAN/Role/Logger.pm, lib/MetaCPAN/Role/Script.pm, lib/MetaCPAN/Script/River.pm, lib/MetaCPAN/Types/Internal.pm, t/script/river.t, t/var/river.json
=> Added script which fetches and indexes river data

lib/MetaCPAN/Document/Distribution.pm, lib/MetaCPAN/Script/Release.pm, t/00_setup.t, t/lib/MetaCPAN/TestServer.pm
this change will prevent the race between setting all releases to
first=0 and then setting first=1 based on a query that depends
on previous put to finish on ES level.
it adds a run of MetaCPAN::Script::First to the setup test,
to ensure all releases are indexed correctly ('first'-wise)
before running the other tests.
=> rework set_first_release + add first script to tests

lib/MetaCPAN/Queue.pm
this simplifies querying the warnings (results will stay null if no warnings/fails)
=> Only add warnings key to 'result' if there are warnings

lib/MetaCPAN/Document/File.pm, lib/MetaCPAN/Document/File/Set.pm, t/server/controller/search/autocomplete.t
This fix will change the 'documentation' mapping from:
```
"documentation" : {
"type" : "string"
}
```
to:
```
"documentation" : {
"fields" : {
"camelcase" : {
"store" : true,
"analyzer" : "camelcase",
"type" : "string"
},
"lowercase" : {
"analyzer" : "lowercase",
"type" : "string",
"store" : true
},
"edge" : {
"analyzer" : "edge",
"type" : "string",
"store" : true
},
"analyzed" : {
"analyzer" : "standard",
"type" : "string",
"fielddata" : {
"format" : "disabled"
},
"store" : true
},
"edge_camelcase" : {
"store" : true,
"type" : "string",
"analyzer" : "edge_camelcase"
}
},
"ignore_above" : 2048,
"index" : "not_analyzed",
"type" : "string"
}
```
This change will also restore the original behavior of `autocomplete`
and fix the test t/server/controller/search/autocomplete.t
It is also needed …
=> Fix 'documentation' mapping

lib/MetaCPAN/Document/File.pm
I can't recall why we removed it, but it is now missing
in metacpan-web (+tests)
=> Put description & abstract info into ES

lib/MetaCPAN/Document/File.pm, lib/MetaCPAN/Document/Release.pm, lib/MetaCPAN/Model/Release.pm, lib/MetaCPAN/Types/Internal.pm
=> remove gid & uid from file stat

lib/MetaCPAN/Script/Backpan.pm, lib/MetaCPAN/Script/Release.pm
many changes to make it useful again (but hopefully we won't need to use it, at least not often)
supports `undo` to move `backpan` status back to `cpan` and `files-only` to update `file` index only.
another change is in Script/Release - rename the cpan files list attribute - it is the opposite of backpan list (as the name suggested)
=> overhaul Script/Backpan

lib/MetaCPAN/Document/Release.pm, lib/MetaCPAN/Server/Controller/Author.pm, t/server/controller/author.t
Per @neilb's request #502 
This is done in the controller.
After playing with this solution *and* with adding the data to the index, I think this is the better one as it will show data in sync with the release index (no need for the Author script to update the numbers) and won't require remapping of the index.
Still, open for comments / suggestions.
=> GET controller for Author, add release count info

lib/MetaCPAN/Server/Controller/Author.pm, t/server/controller/author.t
This will allow us:
1. Serve the links as extra info from the API as well as the WEB.
2. Not concatenate those links using code within the WEB templates.
3. Reuse the links in templates.
Moving functionality from WEB to API.
This was done to allow cleaning up some template code and reuse links.
=> Add author links to author handler response

lib/MetaCPAN/Script/Mapping.pm
we currently ignore this flag which is bad if we want to add new functionality to the script without destroying the mapping.
=> script/mapping: use the provided --delete flag

lib/MetaCPAN/Document/Favorite.pm, lib/MetaCPAN/Model/User/Account.pm, lib/MetaCPAN/Model/User/Session.pm, lib/MetaCPAN/Script/Session.pm
=> removing timestamp references (not supported in ES2.x)

lib/MetaCPAN/Queue.pm, lib/MetaCPAN/Role/Script.pm, lib/MetaCPAN/Script/Latest.pm, lib/MetaCPAN/Script/Queue.pm, lib/MetaCPAN/Script/Release.pm
1. Moved queueing infra. to Role::Script for reuse.
2. Added support for queueing in Script::Latest
(will be useful for later features)
This is part of creating a 'missing latest release' checker, but will also allow extending the use of the queue and make it easily available from all scripts.
=> script/latest: support queueing + code reuse

app.psgi, lib/MetaCPAN/Server.pm, t/lib/MetaCPAN/Server/Test.pm
any reason this added function wasn't used?
the current code relying on the returned value of `require` is not explicit and not as clear.
=> server: use to_app

lib/MetaCPAN/Script/Backpan.pm, t/server/controller/author.t
We should always use the alias of the index ('cpan') rather than the actual index name ('cpan_v1') to allow hot-swapping of newly created indices (in some of the mapping changing cases like #516)
=> Always use the index alias instead of the name

lib/MetaCPAN/Role/Script.pm, lib/MetaCPAN/Script/Ratings.pm, lib/MetaCPAN/Script/Tickets.pm
made shared `ua` and `proxy` attributes available for all scripts.
cleaned up the setting from 2 scripts.
=> script role: ua attribute (lazy) + proxy attribute + cleanup

lib/MetaCPAN/Server/Controller.pm, lib/MetaCPAN/Util.pm, t/server/controller/search/reverse_dependencies.t
=> convert fields output using single_valued_arrayref_to_scalar

.perlcriticrc, lib/MetaCPAN/Document/File/Set.pm
The sort being performed was ignoring the search score.  This short
circuited the 'should' section of the query completely.  This patch
sets the _score as the primary sort criteria, and falls back on the
existing criteria to find the latest, most up-to-date file.
=> Fixes Issue #534

lib/MetaCPAN/Script/Tickets.pm, lib/MetaCPAN/Types/Internal.pm, t/release/bugs.t, t/release/text-tabs-wrap.t
example entry:
``` json
{
"_type": "distribution",
"_source": {
"bugs": {
"github": {
"active": 10,
"source": "https://github.com/ranguard/text-vcard",
"open": 10,
"closed": 30
},
"rt": {
"closed": "6",
"patched": 0,
"active": "2",
"resolved": 6,
"rejected": 0,
"open": 0,
"new": 2,
"source": "https://rt.cpan.org/Public/Dist/Display.html?Name=Text-vCard",
"stalled": 0
}
},
"name": "Text-vCard"
},
"_score": 1,
"_index": "cpan_v1",
"_id": "Text-vCard"
}
```
WIP since after agreeing on this we will need to reindex the `distribution` type - which means deleting it, remapping and rebuilding using the tickets and river scripts.
=> [WIP] distribution: bugs -> rt + github

lib/MetaCPAN/Script/Watcher.pm
watcher doesn't always get the 'latest' setting right.
attempting to solve through queuing (uses separate tasks with priorities to ensure order)
=> script/watcher: use the queue

lib/MetaCPAN/Pod/Renderer.pm, lib/MetaCPAN/Pod/XHTML.pm, lib/MetaCPAN/Server/Controller/Pod.pm, lib/MetaCPAN/Server/View/Pod.pm, metacpan_server.conf, t/release/pod-examples.t
Remove unused X linking feature.  Use built in Pod::Simple::XHTML anchor linking.  Clean up link mapping accessor.
=> Pod linking cleanups

lib/MetaCPAN/Script/Release.pm
With most dists, documentation will get built by set_authorized.  That
isn't reliable though, especially since for the perl dist, we skip that
method.
=> force documentation to get built when indexing

lib/MetaCPAN/Document/File/Set.pm
Drawing on the work from find_download_url, simplify the query to return
modules with valid POD entries.  Return documents where either
the documentation and pod contain the module name, *OR* the
module.associated_pod is set with module.name matching the request path.
Using 'minimum_should_match=1' to ensure that a valid .pm/POD is
selected.
=> Find module query revamp.

lib/MetaCPAN/Server/Controller/Search/Autocomplete.pm, t/server/controller/search/autocomplete.t
To be consistent with API v0 and other v1 endpoints.  No need to leak
more crazy from Elasticsearch than necessary.
=> /search/autocomplete: Collapse single-valued arrays in fields

lib/MetaCPAN/Server/Controller.pm, lib/MetaCPAN/Server/Controller/Author.pm, lib/MetaCPAN/Server/Controller/Favorite.pm, lib/MetaCPAN/Server/Controller/File.pm, lib/MetaCPAN/Server/Controller/Module.pm, lib/MetaCPAN/Server/Controller/Release.pm, lib/MetaCPAN/Util.pm, t/server/controller/module.t
We claim in our docs¹ that our convenience endpoints revert the newer
Elasticsearch behaviour of wrapping single values in arrays.  This makes
that so in more places, specifically the places where the client has
requested a limited subset of fields.
While this may seem like a pain for us and lead to uglier code, think
about it this way: either we do it for our API one time, or every client
that runs into the issue has to do it themselves many times over.
A better solution may exist which centralizes application of
single_valued_arrayref_to_scalar(), but this works for now.
See also GH#580 for an example case.²
¹ https://github.com/metacpan/metacpan-examples/blob/master/README.md#upgrading-from-v0
² https://github.com/metacpan/metacpan-api/issues/580
=> Provide backwards compatibility for clients which request only specific fields

bin/cron/author.sh, bin/cron/backups.sh
since we reverted the index split, this is to prevent cron failure
=> temp. revert cron scripts to use 'old' index

lib/MetaCPAN/Server/Controller/Source.pm
If the API source endpoint is accessed directly, rather than through
st.aticpan.org, provide a more reasonable content type.  Images are
given a the appropriate type for the file, text files are served as
text/plain, and everything else is octet-stream.
=> use better content types for source requests

cpanfile, lib/MetaCPAN/Pod/XHTML.pm, t/pod/renderer.t
Pod::Simple::XHTML does heavy filtering of the link targets it
generates.  This results in many targets being nearly useless for
external use.
Change the targets generated to use less filtering, but also generate
additional targets, one with the first word and one with the old target
like Pod::Simple::XHTML creates.
This is especially useful for pages like perlvar and perlfunc.  Many of
the targets in perlvar consist entirely of characters that are filtered
by Pod::Simple::XHTML.  The targets would therefore look like 'pod5'.
With this change, the unfiltered targets will be available, so linking
to variables will work properly.  The first word target is useful for
perlfunc or any other page that includes parameters function listings.
This will allow links like L<perlfunc/open> to work as …
=> better link targets for headX/item

lib/MetaCPAN/Server/Controller/User.pm
It was throwing an error because after saving the profile because $self->purge_author_key didn't exist, which resulted in the frontend showing an empty profile with a success message. In the frontend the result $res came in with only a `raw` key, but no `error` key, so no error was ever displayed.
Fixes metacpan/metacpan-web#1846.
=> The Fastly role is required to purge_author_key

lib/MetaCPAN/Document/Author.pm, lib/MetaCPAN/Script/Author.pm, lib/MetaCPAN/Script/Mapping/CPAN/Author.pm
This flag will be set through Script::Author (bin/metacpan author).
To deploy we need to update the mapping of the current author type, running (on lw-mc-03):
`curl -X PUT 0:9200/cpan/_mapping/author -d'{"properties":{"is_pause_custodial_account":{"type":"boolean"}}}'`
**BEFORE** merging (can poke me to do it when we agree to merge)
This addresses #620
=> Added 'custodial' flag to 'author' mapping.

lib/MetaCPAN/Document/Author.pm, lib/MetaCPAN/Script/Author.pm
use bulk_helper instead of the model's bulk in the script (with longer timeout, being an hourly cron).
fix time comparison over the author's .json file's mtime - newer is '>' and not '>='.
=> script author: use proper bulk + bug fix

lib/MetaCPAN/Document/Packages.pm, lib/MetaCPAN/Script/Mapping.pm, lib/MetaCPAN/Script/Mapping/CPAN/Packages.pm, lib/MetaCPAN/Script/Packages.pm, lib/MetaCPAN/Server/Controller/Packages.pm, t/00_setup.t, t/lib/MetaCPAN/TestServer.pm, t/packages.t, t/server/controller/packages.t
Added mapping, document, script & tests to support adding
the contents of 02packages.details into its own new type
in the index (in a very similar way to 06perms).
Added modules:
* Document::Packages
document description of a package entry
* Script::Mapping::CPAN::Packages
type mapping for the index
* Script::Packages
a script to read the file & fill the index
* Server::Controller::Packages
an API controller to serve the data
Added test files:
* t/packages.t
* t/server/controller/packages.t
=> Addde type 'packages' to support 02packages.details info

lib/MetaCPAN/Document/Release.pm, lib/MetaCPAN/Server/Controller/Release.pm
a small change to the new endpoint to take author/release values rather than dist name (which only gives results for 'latest')
=> contributors endpoint: make release based (takes author/version)

lib/MetaCPAN/Script/Debian.pm, lib/MetaCPAN/Script/Mapping/CPAN/Distribution.pm
We want to provide the distribution name mappings for Perl
packages to 3rd party sources like Debian.
This commit adds the 'external_package' mapping, and starts
with adding the entry for 'debian' + the script to populate
the data.
=> Added new script and mapping for Debian package name mapping

lib/MetaCPAN/Script/Permission.pm, t/server/controller/permission.t
This will allow cleaning up removed records once in a while
(it requires a longer run time so not suited for every cron run,
and records don't get deleted often anyways).
Usage: add --cleanup flag to the permission script execution.
=> Added cleanup mode for script/permission

lib/MetaCPAN/Script/Package.pm
changes copied from the perms script.
This will allow cleaning up removed records once in a while
(it requires a longer run time so not suited for every cron run,
and records don't get deleted often anyways).
Usage: add --clean_up flag to the package script execution.
=> Added cleanup mode for script/package

lib/MetaCPAN/Role/Script.pm, lib/MetaCPAN/Script/CPANTesters.pm, lib/MetaCPAN/Script/Mirrors.pm, lib/MetaCPAN/Script/Release.pm, lib/MetaCPAN/Script/River.pm
We have a 'ua' object defined as attribute in the script role -
use it instead of creating one everywhere.
=> Use the existing ua object

lib/MetaCPAN/Document/File/Set.pm
If we are given a version spec like '== 1.013030', it should match 1.013_03.
This matches the behavior of the other version specs.
Re: miyagawa/cpanminus#533
=> use numified versions for exact version checks in download_url

lib/MetaCPAN/Server/Controller/User.pm
=> Fix profile update - pass proper 'updated' value

lib/MetaCPAN/Script/Role/External/Cygwin.pm
the returned structure was missing a level ('dist')
=> External: cygwin script (role) returned structure fix

lib/MetaCPAN/Script/CPANTesters.pm, lib/MetaCPAN/Script/Latest.pm
`$self->es` is available... no need for `$self->model->es`
=> Minor cleanup: 'es' is accessible directly

lib/MetaCPAN/Document/Release.pm, lib/MetaCPAN/Server/Controller/Release.pm
This new endpoint is meant to replace current Elasticsearch
query crafted in WEB and passed to the the /release/_search
endpoint.
=> Added /release/requires/MODULE endpoint

lib/MetaCPAN/Document/Contributor.pm, lib/MetaCPAN/Document/Release.pm, lib/MetaCPAN/Script/Contributor.pm, lib/MetaCPAN/Script/Mapping.pm, lib/MetaCPAN/Script/Mapping/Contributor.pm, lib/MetaCPAN/Script/Release.pm, lib/MetaCPAN/Script/Role/Contributor.pm, lib/MetaCPAN/Server/Controller/Contributor.pm, t/server/controller/contributor.t, t/server/controller/package.t, t/server/controller/permission.t
New type and supporting code & test to fill/fetch the
release contributors info to/from the index.
* MetaCPAN::Script::Mapping::CPAN::Contributor
Added for type mapping for Elasticseach
* Script::Contributor
Added for data filling of release contributors.
Script can run in different modes:
--all          # run for all releases in the 'release' type
--distribution # run for all releases matching a given distribution
--release      # run for a single release (format: PAUSEID/DISTRIBUTION-VERSION)
* Script::Release
Updated to store contributor info for processed releases
* Script::Role::Contributor
Added to support common functionality shared by the scripts
for handling contributors info fetching/updating.
* Document::Contributor
Model representation of the new type.
* …
=> Introducing 'contributor' type (release contributors info)

lib/MetaCPAN/Script/Role/External/Debian.pm
The useful call is one line below. This is probably some remain from
development.
=> Remove useless call to dist_for()

lib/MetaCPAN/Script/External.pm, lib/MetaCPAN/Script/Mapping/CPAN/Distribution.pm, lib/MetaCPAN/Script/Role/External/Fedora.pm
It loops over the result pages of the API request for all
approved packages.
The role is added to the main 'external' script, and
external_package.fedora is added to the elasticsearch mapping.
=> Add a new role to collect Fedora-packaged CPAN distributions

lib/MetaCPAN/Script/External.pm, lib/MetaCPAN/Script/River.pm
This PR is for 2 issues with scripts that both update 'distribution'
1. River is making destructive updates, deleting the external_package data.
2. External is not creating new records.
=> Fix type updates in distribution

lib/MetaCPAN/Document/Author.pm, lib/MetaCPAN/Server/Controller/Author.pm
In WEB use, the query runs against multiple user ids.
This change first fixes the query to support multi-value check
(term -> terms).
Added another support for this endpoint which takes the users'
ids through a 'user' URL param: 'user=USER_ID1&user=USER_ID2...'
If you don't see a need for the URL param support I can drop it (I found it useful for manual testing using curl but WEB will probably not need it).
=> Improved /author/by_user endpoint

lib/MetaCPAN/Document/Favorite.pm, lib/MetaCPAN/Server/Controller/Favorite.pm
this change will:
1. allow passing `size` parameter from the `/favorite/by_user` endpoint to the query  
2. rename the inner filtering query to 'no_backpan' which better reflects its function (filtering out distributions with only backpan releases)
3. pass `size` value to no_backpan to get all matches (rather than default ES results limit)
=> favs by user query fix

lib/MetaCPAN/Document/Release.pm, lib/MetaCPAN/Server/Controller/Release.pm
This new endpoint will replace an Elasticsearch sent from
WEB.
=> Added /release/latest_by_author/PAUSEID

lib/MetaCPAN/Document/Permission.pm
Not sure why the terms query doesn't work properly, **I suspect
an Elasticsearch bug** (following its documentation it **should** work).
=> Corrected permission query

lib/MetaCPAN/Document/Author.pm
For more reuse in WEB, we need extra info from the author type.
Removing the fields list and returning _source will allow more
use cases.
=> Return all author info for endpoint /author/by_user/USER

lib/MetaCPAN/Document/Release.pm, lib/MetaCPAN/Server/Controller/Release.pm, lib/MetaCPAN/Server/Controller/ReverseDependencies.pm
Added 2 new endpoints:
* /reverse_dependencies/dist/DISTRIBUTION
moved query from WEB (+ will replace the current complicated endpoint in /search/reverse_dependencies)
* /reverse_dependencies/module/MODULE
copied (& later will remove) current /release/requires endpoint
Added a new controller Controller/ReverseDependencies.pm to
later replace the current Controller/Search/ReverseDependencies.pm
(will be removed with all supporting code once WEB is set to
point to new endpoints)
Note: the cleanup part of the current endpoint will be submitted after this PR is deployed and the code in WEB will be changed to use it.
=> Added new /reverse_dependencies API endpoints

lib/MetaCPAN/Document/Release.pm
To allow the template in WEB to read the data, the release info
needs to be passed with full _source data.
=> Correct /reverse_dependencies/dist output

lib/MetaCPAN/Server/Controller/Permission.pm
the module list is sent from WEB through the body of the request - I still want to support query params for it but we can hit a size limit for a long list.
=> /permission/by_module : read modules list from request body

lib/MetaCPAN/Document/Release.pm, lib/MetaCPAN/Server/Controller/Release.pm
This will replace query sending from WEB.
This commit also removes /release/requires endpoint which was
already moved to the new ReverseDependencies controller.
=> Added /release/recent API endpoint, removed /release/requires

lib/MetaCPAN/Script/Mapping.pm
This will only affect VM.
Apparently I forgot to list Mirror type mapping and we don't
catch this with tests.
=> Script/Mapping: add mirror type mapping

lib/MetaCPAN/Document/Release.pm
There is no reason to return an arrayref with one element.
Changed the returned structure from:
{ total => ... , took => ... , releases => [ {RELEASE_DATA} ] }
to:
{ total => ... , took => ... , release => {RELEASE_DATA} }
=> /release/latest_by_distribution: return one element

lib/MetaCPAN/Document/Release.pm
There is no reason to return an arrayref with one element.
Changed the returned structure from:
{ total => ... , took => ... , releases => [ {RELEASE_DATA} ] }
to:
{ total => ... , took => ... , release => {RELEASE_DATA} }
=> /release/by_author_and_name: return one element

lib/MetaCPAN/Document/Favorite.pm
For easier adoption by WEB, the returned results are better in
hashes rather than arrays.
=> /favorite/agg_by_distributions: change result structure

lib/MetaCPAN/Document/Release.pm
=> /release/modules: no single-value collapsing on 'modules'

lib/MetaCPAN/Document/Rating.pm
Make the distributions output a hash.
This will make it easier to adopt by WEB.
=> /rating/by_distributions: change output structure

lib/MetaCPAN/Model/Search.pm, lib/MetaCPAN/Server/Controller/Search/Web.pm, lib/MetaCPAN/Server/Model/Search.pm
This will simplify the reading of /search/web/simple output by
extracting the first element and eliminating the need for WEB
to read an ES output structure.
=> Added /search/web/first API endpoint

lib/MetaCPAN/Document/Release.pm, lib/MetaCPAN/Server/Controller/Changes.pm, lib/MetaCPAN/Server/Controller/Diff.pm, lib/MetaCPAN/Server/Controller/Package.pm, lib/MetaCPAN/Server/Controller/Release.pm
Keep the controller code concise and unaware of the data structure.
=> Controller::Release::find - move data handling to Document module

.dockerignore, .gitignore, Dockerfile, app.psgi, bin/prove, lib/MetaCPAN/Server.pm
This adds a `Dockerfile` so that the app can be built as a Docker image.
docker build -t metacpan-api .
One can start a development server on Docker via
docker run -p 5000:5000 -v /path/to/metacpan-api:/metacpan-api -it metacpan-api
although additional configuration may be necessary (e.g. linking a CPAN mirror and ElasticSearch to the container, setting up the indices/mappings, and importing metadata.)
This is extracted and rewritten from metacpan-docker to allow independent usage (i.e. one doesn't need to source any other repo in order to build this as a Docker image.)
This is part of an effort to Dockerize MetaCPAN (including the web frontend and ElasticSearch services.)  See https://github.com/metacpan/metacpan-docker/pull/11 for more info.
=> Dockerize the MetaCPAN

lib/MetaCPAN/Document/Release/Set.pm, lib/MetaCPAN/Model/#Search.pm#, lib/MetaCPAN/Role/HasRogueDistributions.pm, lib/MetaCPAN/Script/Author.pm, lib/MetaCPAN/Script/Release.pm, lib/MetaCPAN/Script/Watcher.pm, lib/MetaCPAN/Server/Controller/Activity.pm, lib/MetaCPAN/Server/Controller/Author.pm, lib/MetaCPAN/Server/Controller/Changes.pm, lib/MetaCPAN/Server/Controller/Contributor.pm, lib/MetaCPAN/Server/Controller/Diff.pm, lib/MetaCPAN/Server/Controller/Favorite.pm, lib/MetaCPAN/Server/Controller/Mirror.pm, lib/MetaCPAN/Server/Controller/Package.pm, lib/MetaCPAN/Server/Controller/Permission.pm, lib/MetaCPAN/Server/Controller/Rating.pm, lib/MetaCPAN/Server/Controller/Release.pm, lib/MetaCPAN/Server/Controller/ReverseDependencies.pm, lib/MetaCPAN/Server/Controller/User.pm, t/release/pm-PL.t
Removed calls to 'raw' (ESX::Model) for the new API endpoints
which don't use the model for querying.
Changed all 'inflate(0)' calls to 'raw' (does the same) for
consistency.
Moved 'raw' calls from controllers back to the document where
possible (some cases will be dealt with later).
=> Removed needless calls to model settings (raw)

lib/MetaCPAN/Server/Controller/Favorite.pm
read_param is meant for mandatory params as it detaches when
value is not found.
In this case, 'user' is an optional param and always single-value,
so we don't need to use it.
this will solve the problem of ++ count not showing in /pod pages. will merge once tests pass
=> favorite/agg_by_distributions: 'user' --> optional param

lib/MetaCPAN/Server.pm, lib/MetaCPAN/Server/Controller/Activity.pm, lib/MetaCPAN/Server/Controller/Author.pm, lib/MetaCPAN/Server/Controller/Contributor.pm, lib/MetaCPAN/Server/Controller/Favorite.pm, lib/MetaCPAN/Server/Controller/File.pm, lib/MetaCPAN/Server/Controller/Mirror.pm, lib/MetaCPAN/Server/Controller/Package.pm, lib/MetaCPAN/Server/Controller/Permission.pm, lib/MetaCPAN/Server/Controller/Rating.pm, lib/MetaCPAN/Server/Controller/Release.pm, lib/MetaCPAN/Server/Controller/ReverseDependencies.pm, lib/MetaCPAN/Server/Controller/Search/Autocomplete.pm
To remove the need to copy-paste the same pattern of reading data
and then checking it before stashing (to avoid errors), the
pattern was made into a single reusable method available for
the controller.
=> Added controller method for improving/simplifying data stashing

lib/MetaCPAN/Server/Controller/Release.pm
/release/latest_by_distribution & /release/versions are affected.
This will (hopefully) solve the caching issue we have with
distributions with new releases indexed.
=> Added surrogate key for 'dist' for purging in 2 endpoints

lib/MetaCPAN/Server/Controller/ReverseDependencies.pm
Added the missing page, page_size & sort params passed from the
endpoint to the querying method.
fixes #736
=> Pass missing params to reverse_dependencies

lib/MetaCPAN/Document/File/Set.pm, lib/MetaCPAN/Document/Release/Set.pm, lib/MetaCPAN/Server/Controller/Author.pm, lib/MetaCPAN/Server/Controller/Changes.pm, lib/MetaCPAN/Server/Controller/Release.pm
moved some more data handling code out of the controllers into the document modules.
once merged, at least one new endpoint (release.by_author_and_name) could be cleaned out (after WEB switches to 'get')
=> more api refactoring

cpanfile
This is used by OrePAN2. We want the latest version of MetaCPAN::Client
so that it doesn't try to connect to the v0 API when building the
darkpan.
=> Make MetaCPAN::Client an explicit test dep.

lib/MetaCPAN/Document/Release/Set.pm
'sort' param sent to reverse_dependencies is currently broken as
it gets a structure passed through the URL which gets stringified.
With this change the new form of the param will be like:
?sort=name:desc
?sort=date:asc
=> Accept sort param in a URL friendly form

docs/indexing.md
This ¶ was apparently left over from last year!
=> Indexing doc: Describe release.status and file.status

cpanfile.snapshot
This was mostly done in 678f450139a but we never upgraded the snapshot,
so the tests are still messy looking.
=> Upgrade to latest version of MetaCPAN::Client

lib/MetaCPAN/Document/Favorite/Set.pm, lib/MetaCPAN/Query/Favorite.pm, lib/MetaCPAN/Query/Role/Common.pm
This new namespace will be used to hold ES query code that
is not coupled with the model and will eventually replace
the model.
As a first step, moving the contents of MetaCPAN::Document::Favorite::Set
to the new namespace.
This will be used to serve a shared access for the autocomplete method.
=> Created MetaCPAN::Query::*

lib/MetaCPAN/Document/File/Set.pm
Returned results are first queried from the suggester, filtered for relevance (authorized etc) and then sorted as:
* exact match
* by ++
* by suggester score
* by length
* by ascii
in descending importance.
=> Improve autocomplete when using suggester

.travis.yml
Travis automatically uploads these according to their build number, so we don't need to allow for duplicates.  We may want to set up an occasional purge, though.  We can do that later.
=> Add Travis build artifacts

lib/MetaCPAN/Query/Release.pm
This will take into account contributors that do not have @cpan.org emails but still have emails associated with their author info
=> Contributor: check emails against authors data

lib/MetaCPAN/Server/Controller/Pod.pm, lib/MetaCPAN/Server/View/Pod.pm
Allows converting pod to HTML in the same way MetaCPAN does.
=> add pod_render endpoint

lib/MetaCPAN/Document/File.pm, lib/MetaCPAN/Document/Release.pm, lib/MetaCPAN/Script/Mapping/CPAN/File.pm, lib/MetaCPAN/Script/Mapping/CPAN/Release.pm, lib/MetaCPAN/Script/Release.pm
Added to both release and file types (which is also /module in API)
Field will be set by the 'release' script.
This PR is to address #572 
Note: after merge - need to run a one-off run to update field for existing releases
=> Added 'deprecated' field

lib/MetaCPAN/Script/CPANTestersAPI.pm
increase the bulk helper timeout. 
@preaction do you think 30m is enough?
=> Script::CPANTestersAPI - increase bulk_helper timeout

lib/MetaCPAN/Document/File/Set.pm
Make suggested result take 'deprecated' field into account.
(So for example MetaCPAN::Client will appear before MetaCPAN::API)
=> Suggester use deprecated field

lib/MetaCPAN/Document/File/Set.pm
This is because I've seen cases where ES returns the quoted
strings "true" & "false" where in others the JSON true & false.
Normalizing to 0 & 1 ensures the correct sorting we do based
on this field in the results from the autocomplete suggester.
=> Map values of 'deprecated' to 0,1 to ensure correct sorting

lib/MetaCPAN/Server/Controller/Release.pm
This endpoint was set temporarily to replace a query in WEB
(which no longer uses it).
It has the same functionality as the 'get' endpoint -
/release/AUTHOR/RELEASE_NAME
=> API: Removed redundant endpoint /release/by_author_and_name

lib/MetaCPAN/Document/Cover.pm, lib/MetaCPAN/Document/Cover/Set.pm, lib/MetaCPAN/Query/Cover.pm, lib/MetaCPAN/Script/Cover.pm, lib/MetaCPAN/Script/Mapping.pm, lib/MetaCPAN/Script/Mapping/Cover.pm, lib/MetaCPAN/Server/Controller/Cover.pm
This will add the mapping and the script to be used as a cronjob to collect cover data into ES.
The data will be collected into its own index/type (cover/cover)
The second commit adds an API endpoint to support fetching release coverage info.
=> Added mapping+script+endpoint for collecting CPAN Cover info into MetaCPAN

lib/MetaCPAN/Query/File.pm
This enables https://github.com/metacpan/metacpan-web/issues/1779 by letting `interesting_files` pick up Contributing files as well as Hacking files on older dists, and relaxes the filter to let the function search for these files (and more) throughout the release dist.
=> Add more CONTRIBUTING/HACKING docs as interesting files

lib/MetaCPAN/Model/Release.pm, lib/MetaCPAN/Query/File.pm
Rather than allow any files to match by its filename alone, split the
list in two.  One list of files that must be in the root directory
(mostly files with no extension, markdown files, or ALL CAPS files).
For pod or pm files, allow them to be in subdirectories.  Eliminate a
few top level directories that are commonly used for special cases and
not part of the dist metadata or module list.
Also update the code that picks a changelog for a release to use equivalent logic.
=>  improve choices for interesting files

lib/MetaCPAN/Model/Search.pm
This greatly reduces the number of ES queries needed to do searches, down to just one for both collapsed and expanded searches.  The collapsed search can be done with an aggregation.
The order of the results can be slightly different.
Fixes #823
=> Search simplification for speed

lib/MetaCPAN/Model/Search.pm, lib/MetaCPAN/Server/Controller/Search/Web.pm, t/model/search.t
The existing search end points gives an array of arrays.  For collapsed
searches, each inner array represents a dist.  Because these arrays are
stored directly without a wrapping object, there is nowhere to store
additional data about the results.
For collapsed results, there is little reason to include all of the
inner file results.  For the metacpan front end, we only need the first
5 or so, as well as the count.  There isn't anywhere to store the count
without introducing a wrapping object for each search result.
The new end point returns an array of objects.  The objects include the
distribution name, the top five inner hits, and the total amount of
inner hits.
=> new search end point with total collapsed entries

lib/MetaCPAN/Model/Release.pm
In some cases (see #812) release have many files and no provides
this timeout is simply not enough in those cases and it's timing
out is silenced in try/catch which causes a partial indexing with
missing 'modules' section which causes no 'latest' bit marking
which makes the release not discoverable.
=> Increase alarm for modules extraction from files

lib/MetaCPAN/Script/Role/External/Debian.pm
The address and credentials have changed. See https://udd-mirror.debian.net/ for details.
=> Update the DSN to the UDD

lib/MetaCPAN/Script/Release.pm
In some cases we have to deal with incorrect data based on reindexing after permissions have changed.
In those cases we may want to reindex (manually) while forcing the check of authorized to 'true' knowing this was the case at the time of the original release.
See [GH#2117](https://github.com/metacpan/metacpan-web/issues/2117)
=> Script::Release - allow forcing authorized flag

cpanfile.snapshot
This module is required by File::HomeDir but only when installed on
a Mac. It's an optional prerequisite. Having the definition in the
cpanfile.snapshot allows carton install --deployment to install
Mac::SystemDirectory if required, and has no impact if it is not.
=> Add definition for Mac::SystemDirectory

lib/MetaCPAN/Server/Controller/Search/Web.pm
/search/web is not used anymore (since June 2018)
This is first step for removing v2 after Web starts
using /search/web again.
=> Consolidate /search/web & /search/web/v2

.travis.yml
So that tests don't fail if a tarball cannot be fetched.
=> Add Travis DarkPAN caching

.travis.yml
Instead of running the Travis ES service, which is known to have issues, create the ES service in a docker container using the official image for 2.4.
=> Replace Travis ES Service with a docker container

lib/MetaCPAN/API.pm
At some point there will be an update to nginx that no longer strips the
`/v1` from the path. When this happens, having this mount point in place
will allow the fall through to the Catalyst app to continue.
Retaining the `/v1` path fixes an issue where the Mojolicous application is unable to
validate the specification for OpenAPI because the defined base path
does not exist.
=> Add route for `/v1` path

Dockerfile
When the container is done being built, start the Mojolicious API application instead of starting the Catalyst application (which will start as part of the Mojolicious application). 
This container is using `morbo` in order to allow development of the API along side the running container.
The Mojolicious application waits for the database container to be started and for PostgreSQL to be accessible before starting, otherwise the API throws an error message that the database is inaccessible.
=> Start Mojolicious API application

cpanfile, cpanfile.snapshot, lib/MetaCPAN/Model.pm
Log::Any is used by Search::Elasticsearch, so we should connect it to
our standard logger.
=> Log::Any via Log::Log4perl

lib/MetaCPAN/Document/Release/Set.pm, lib/MetaCPAN/Query/Release.pm, lib/MetaCPAN/Server/Controller/Changes.pm
Context: https://github.com/metacpan/metacpan-web/issues/2142
I wished to mixin the latest changelog for each recent releases in `/feed/recent`, but with existing APIs it'd take N requests in order to do that.
In order to minimize the number of round-trips betwenn API and Web, I added this API endpoint to retrieve the changelog content of the given list o "release" parameter. This still maps to N Elasticsearch queries but I'm guessing that's OK.... if not I can improve that as well.
Here's how it looks like:
```
curl 'http://localhost:5000/changes/by_releases?release=GUGOD/Hijk-0.28&release=GETTY/AnyEvent-ITM-0.003'
{
"changes" : [
{
"changes_file" : "Changes",
"changes_text" : "==================================================\nChanges from 1745-02-09 00:00:00 +0000 to …
```
=> Add a new API: /changes/by_releases

Dockerfile, wait-for-it.sh
The script to wait for the database server to be up needs to be included
as part of the container in order for it to be executed. This change
adds the script and copies it into position within the container.
=> Add wait-for-it.sh script to container

lib/MetaCPAN/Script/Latest.pm, lib/MetaCPAN/Script/Queue.pm, lib/MetaCPAN/Script/Release.pm
The previous behaviour was to run this job immediately after the
indexing job finished, but this was proabably too early in almost all
cases.  Here we wait for a while and then try setting the flag.
=> Take several (delayed) passes at setting the "latest" flag

lib/MetaCPAN/Query/Release.pm
Otherwise Elasticsearch returns 10 hits by default.  Since this
'by_author_and_names' routine is the backend of '/feed/recent' and
responds up to 100 hits, this tweak can reduce the amount of roundtrip
bteewn frontend and backend.
I wish to utilize this together with https://github.com/metacpan/metacpan-web/pull/2157
=> Set th "size" of resultset to be the same as input size.

lib/MetaCPAN/Model/Release.pm, lib/MetaCPAN/Script/Release.pm
This is fixing the flood of errors exposed by the Log4Perl change.
=> Check if distribution exists before creating

Dockerfile
Running `index-cpan.sh` requires that `rsync` is installed within the
container. It was previously removed from the `metacpan-base` image, and
as the api is the container that will make use of it (or a container
based on its image), adding it into the image.
=> Add rsync to container for index updates

lib/MetaCPAN/API/Controller/Cover.pm, lib/MetaCPAN/API/Model/Cover.pm, lib/MetaCPAN/API/Plugin/Model.pm, lib/MetaCPAN/Script/Cover.pm, root/static/definitions/common.yml, root/static/requests/cover.yml, root/static/v1.yml, t/00_setup.t, t/api/controller/cover.t, t/lib/MetaCPAN/TestServer.pm, t/server/controller/cover.t, t/var/cover.json
Using `MetaCPAN::Model::User` and `MetaCPAN::Model::Download` as examples, convert `MetaCPAN::Query::Cover` into a model, add the plugin, controller, and tests, and create the OpenAPI spec to drive it.
=> Create Model, Controller and spec for Cover

lib/MetaCPAN/Query/Release.pm
This hardcoded limit of 250 releases appears to be preventing https://www.cpan.org/src/README.html from displaying older versions of the perl distribution. It is using http://search.cpan.org/api/dist/perl which then queries https://fastapi.metacpan.org/v1/release/versions/perl, which is missing many older versions. This also affects `perlbrew available` which uses this page to display available releases. This is a shot in the dark so please verify this is the correct location to change.
=> Increase release limit for perl versions endpoint

.env
We do not need to restart the webapp every time there
is a log entry in var/log/metacpan.log otherwise
we will end up always restarting in development.
This is similar to the fix applied to the docker repo
Upstream-URL:
https://github.com/metacpan/metacpan-docker/pull/51
=> Do not refresh morbo app when log is updated

.travis.yml, etc/metacpan_testing.pl, t/lib/MetaCPAN/Server/Test.pm, t/lib/MetaCPAN/TestServer.pm
Since moving to the docker env we need to make sure tests don't
clobber data in the dev elasticsearch instance but use the
elasticsearch_test one.
=> Use ES_TEST in tests

lib/MetaCPAN/Document/File/Set.pm, lib/MetaCPAN/Document/Release.pm, lib/MetaCPAN/Model/Archive.pm, lib/MetaCPAN/Model/Release.pm, lib/MetaCPAN/Query/Release.pm, lib/MetaCPAN/Script/Mapping/CPAN/Release.pm, t/server/controller/download_url.t
Relates to #327 
This will add `checksum_md5` & `checksum_sha1` mappings *definitions* (will require manually adding the mappings in production - I can take care of that once approved) to the `release` type (I don't think the `file` type level is the right place to hold it though it has the `download_url` copy as it may confuse people to think these are the checksums of the files).
Is `Digest::file` the right module to use? any other suggestions?
=> Added checksums (md5/sha256) to release archives + download_url endpoint

lib/MetaCPAN/Script/Release.pm
To allow for future use of a Raku subdir, as in https://github.com/andk/pause/issues/346
=> Skip indexing distributions in a Raku subdir

lib/MetaCPAN/Model/Search.pm
fixes #952 - ES reserved chars in non-simple string search require escaping.
(needs tidy)
=> escape reserved chars in search term

lib/MetaCPAN/Model/Search.pm
This is a quick fix for now.  It might be helpful to have a larger discussion about how to treat colons, but this would restore the status quo while keeping the fix for slashes in searches in place.
=> Fix author/dist/module searches

lib/MetaCPAN/Document/File/Set.pm, lib/MetaCPAN/Query/File.pm, lib/MetaCPAN/Server.pm, lib/MetaCPAN/Server/Controller/Release.pm
The existing interesting_files end point had a long list of files to
include, with inconsistent rules for what file extensions and
capitalization would be allowed.  It also would just give the files back
in a single list.  The code for finding change logs partly reproduced
this.
Unify the logic for the files we search for, with consistent rules for
file extensions, capitalization, and handling of special dists like
"perl".  Keep the different types of files categorized so that
interesting_files can both filter the files it is querying for, and
adding a new end point files_by_category to easily find the files of a
specific type, like was previously possible for change logs.  Install
files and contributing docs are now listed on the front end, so this
should make it easier for them to find …
=> add files_by_category end point

.travis.yml, bin/docker-elasticsearch, t/00_setup.t
Extracting this script from `.travis.yml` has allowed me to get a locally-running Docker container with ES, that together with setting environment variables from there, to run the tests successfully:
```sh
bin/docker-elasticsearch /tmp/metacpan.yml /tmp/es 127.0.0.1:9200
ES=localhost:9200 ES_TEST=localhost:9200 METACPAN_SERVER_CONFIG_LOCAL_SUFFIX=testing prove -lr t
```
Notes: I've removed what looks like an unnecessary `mkdir`, and taken `-O` off `curl`. Also, `t/00_setup.t` was doing `remove_tree` to ensure clean start, but in the default safe mode, that fails, so I've made it not be "safe".
=> Extract ElasticSearch Docker container build from CI config into script

git/hooks/pre-commit, lib/MetaCPAN/Model/Search.pm, t/api/controller/admin.t, t/model/search.t
The previous fix (https://github.com/metacpan/metacpan-api/commit/225749b6e54a29ee7a34b835d01f0918e7448b7f) had two issues:
- it matched spaces, so it quoted them - I was unable to make it not do this, so I removed all the whitespace and the `x` flag
- it only quoted the first character it found, not all
This is hopefully a fix, and hopefully will also fix the -web tests.
=> Search fix

.travis.yml
Main (snapshot) tests take ~10 mins, coverage takes ~30 (plus reports many `unexpected OP_CUSTOM (is_plain_hashref) at /home/travis/perl5/perlbrew/perls/5.22.4/lib/5.22.4/B/Deparse.pm line 1538.`). Therefore it is a separate job that is "allow failure", to not slow CI down.
=> Enable Travis coverage as separate job

README.md
Since the current link is to https://github.com/metacpan/metacpan-api/wiki/API-docs which sends you back to `docs/`
=> Don't send people to the wiki then back out

lib/MetaCPAN/Query/Release.pm, lib/MetaCPAN/Server/Controller/Release.pm
This PR is addressing #927 
---
This commit adds support for two new parameters to the release/versions endpoint.
Examples:
https://fastapi.metacpan.org/v1/release/versions/perl?plain=1
https://fastapi.metacpan.org/v1/release/versions/perl?versions=5.26.0,5.30.1
https://fastapi.metacpan.org/v1/release/versions/perl?plain=1&versions=5.26.0,5.30.1
=> GH#927 Add plain mode + version filter to release/versions endpoint

lib/MetaCPAN/Query/Release.pm, t/server/controller/release.t
When using versions (CSV) you can use 'latest' as a valid verison number
to refer to the release marked with 'status=latest'
Examples:
https://fastapi.metacpan.org/v1/release/versions/perl?versions=latest
https://fastapi.metacpan.org/v1/release/versions/perl?versions=5.26.0,latest
=> added support for 'latest' in versions param of release/versions/DIST

lib/MetaCPAN/Query/Release.pm
Added stricter check for type of relationship.
This should (hopefully) address the issue in #957
=> Fix reverse_dependency query

lib/MetaCPAN/Model/Search.pm
Matches modules that are marked as `deprecated: true` in ElasticSearch, and gives them a negative boost in the search results.
Relates to metacpan/metacpan-web#1435
=> Add a negative boost to Deprecated modules, when searching MetaCPAN.

lib/MetaCPAN/Document/File/Set.pm
As per discussion in metacpan/metacpan-web#2438, the ElasticSearch indices that back the MetaCPAN API have been updated to now consistently return Boolean values for the `deprecated` field.
Thus, no longer need this check for string `"true"` or `"false"` values, which would then be cast accordingly to a proper boolean.
**Unfortunately**, this is one of those things that I am unable to test from here (as the ElasticSearch indices spun up locally by `metacpan-docker` have only ever returned proper booleans and not boolean strings).
Thus, I **highly encourage** someone w/access to the underlying Production ElasticSearch indices to test this out themselves prior to merging.
The function impacted here is the "search autocomplete", and the `deprecated` attribute is used to help sort the results …
=> No longer need this boolean re-cast; ES indexes return proper bools now.

lib/MetaCPAN/Script/Mapping/CPAN/Distribution.pm
This is just for future reference, the index (type) mapping is already done.
=> Added bus_factor to the mapping file

docs/API-docs.md
Updates the documentation to the ElasticSearch 2.4 reference in order to
fix the 404 errors.
```
$ git show HEAD --word-diff | grep -o '\[[^[]*\[-.*+}'  | grep -o 'https://www.elastic.co/[^\)]*'  | xargs -n1 title.pl
Query DSL | Elasticsearch Guide [2.4] | Elastic https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl.html
Scroll | Elasticsearch Guide [2.4] | Elastic https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-scroll.html
Search Type | Elasticsearch Guide [2.4] | Elastic https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-search-type.html#scan
Bool Query | Elasticsearch Guide [2.4] | Elastic https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-bool-query.html
```
=> Update links to ElasticSearch documentation

lib/MetaCPAN/Query/File.pm
Otherwise directories that are used by releases such as:
- <https://metacpan.org/source/SRI/Mojolicious-9.18/examples>
- <https://metacpan.org/source/ETJ/PDL-2.048/Example>
will not have their examples listed on their release page.
Fixes <https://github.com/metacpan/metacpan-web/issues/2427>.
---
Also:
Add demo/demos as category example
For example, found in the release:
- <https://metacpan.org/source/DCONWAY/Regexp-Grammars-1.057/demo>
=> File queries shared by path and prefix for category example

lib/MetaCPAN/Server/Action/Deserialize.pm, lib/MetaCPAN/Server/Controller.pm, t/server/controller/bad_content.t
If there is an error while deserializing, it is nicer to respond with a
JSON response, rather than plain text. Use a custom Deserialize action
class, which puts the error into the stash where either the Serialize
action class or the JSON view expects. And then skip the rest of the
request.
=> respond to deserialization errors with json

lib/MetaCPAN/Document/File/Set.pm
Releases on backpan should not be allowed unless an explicit version is
given. This appears to have been a mistake when converting the query
from cpanminus.
=> fix filters in download_url end point

lib/MetaCPAN/Role/Script.pm, lib/MetaCPAN/Script/Mapping.pm
For the issue detected and documented at
[MetaCPAN API - Indexing failed](https://github.com/metacpan/metacpan-docker/issues/47)
there are several features needed in the `MetaCPAN::Script::Runner` scripts
Seen in this Test Report
[Dependency on _MetaCPAN API_](https://github.com/bodo-hugo-barwich/metacpan-docker/runs/4060036486?check_suite_focus=true#step:5:10)
[_GitHub_ Testing Workflow](https://github.com/bodo-hugo-barwich/metacpan-docker/pull/2)
the successful test depends on a development in _MetaCPAN API_.
This change implements several features:
* in `MetaCPAN::Role::Script`:
* `exit_code`
* `cluster_info`
* `indices_info`
* `aliases_info`
* `arg_await_timeout` (triggered with `--await`)
* `await()` Method
* `check_health()` Method
The Developer Documentation is also a bit more …
=> ElasticSearch Availabilty Check and Mapping Self-Check

bin/metacpan, lib/MetaCPAN/Script/Mapping.pm, lib/MetaCPAN/Script/Runner.pm, t/lib/MetaCPAN/Script/MockError.pm, t/lib/MetaCPAN/TestServer.pm, t/script/runner.t
To satisfy the requirement for `MetaCPAN::Script::Runner::run()` to return a ` TRUE ` value but also keep track of the Exit Code of the Plugin Modules and probable exceptions that happened in the execution the return value was changed:
```
$ git diff master lib/MetaCPAN/Script/Mapping.pm
diff --git a/lib/MetaCPAN/Script/Mapping.pm b/lib/MetaCPAN/Script/Mapping.pm
index 7e4f47f2..f709aef7 100644
--- a/lib/MetaCPAN/Script/Mapping.pm
+++ b/lib/MetaCPAN/Script/Mapping.pm
@@ -129,7 +129,7 @@ has delete_from_type => (
);
sub run {
-    my $self   = shift;
+    my $self = shift;
if ( $self->await ) {
$self->delete_index if $self->arg_delete_index;
@@ -151,9 +151,8 @@ sub run {
}
}
-    # Correctly reaching this point it will end the application
-    # with the set …
```
=> Capture Exit Code in MetaCPAN::Script::Runner

lib/MetaCPAN/Server/Controller/Login/GitHub.pm
GitHub does no longer accept the access token as a query string. The token needs to be passed in the Authorization header instead. Fixes metacpan/metacpan-web#2595 with regard to GitHub.
=> Pass the GitHub access token in the Authorization header

lib/MetaCPAN/Document/File/Set.pm
The documented_modules method is only used for one thing currently,
which is finding all of the modules that should be used for link
mappings. This immediately filters for modules that have documentation.
This should instead be part of the filter sent to elasticsearch, to
avoid non-documented files overrunning our result size of 999.
=> documented_modules should filter for modules with documentation

.github/workflows/update-snapshot.yml
See also: https://github.com/skaji/cpm/pull/219
On April 29th, git.io url redirection service was read-only.
https://github.blog/changelog/2022-04-25-git-io-deprecation/
cpm recommends changing the URL to install, so I followed the recommendation.
https://github.com/skaji/cpm/blob/61df877db9fd6f30f281e51df43a44bf555676ee/Changes#L7
=> Replace git.io shortener links to full address

.github/workflows/update-snapshot.yml
"Update cpanfile.snapshot" keeps failing, mainly due to permissions.
https://github.com/metacpan/metacpan-api/runs/6745584648?check_suite_focus=true
This problem could be solved by running on a perl container image, as other perl libraries use in their actions.
<https://github.com/skaji/cpm/blob/61df877db9fd6f30f281e51df43a44bf555676ee/.github/workflows/test.yml#L24-L25>
=> use perl 5.36 container

lib/MetaCPAN/Document/Author.pm
The field is_pause_custodial_account is declared as a Bool, but this type restricts values to empty string, zero or one.  When served as a JSON document, this gets converted to a JSON boolean 'true' or 'false'.  When parsed back to Perl, this becomes a JSON::Boolean object.  JSON::Boolean objects do not match the type constraint of Bool, and cannot be used to construct ..Document::Author. In particular, this is breaking the ability to update the profiles of metacpan in metacpan/metacpan-web/issues/2694
Adding `coerce => 1` allows the JSON::Boolean to get transformed to '' or 1, permitting a round trip without changing any representation of the boolean publicly or internally.
Other possible solutions:
- Change the 'Bool' type constraint to allow JSON::Boolean.  This has a side effect of …
=> Apply coercion to allow round-trip of boolean through JSON

.github/workflows/docker-push.yml
This really should also happen in CircleCI, but let's add it here as
well so that we can easily push an updated image when we need to.
=> Add a Docker push workflow

lib/MetaCPAN/Role/Script.pm, lib/MetaCPAN/Script/Mapping.pm, t/00_setup.t, t/lib/MetaCPAN/TestServer.pm, t/script/mapping.t
This implements the deep comparison of the deployed mappings in the _ElasticSearch_ cluster and the definitions in the project.
```
$ bin/metacpan mapping --verify              # compare deployed indices and aliases with project definitions
```
This will show automatic unexpected adjustments made by the _ElasticSearch_ engine which do not correspond to the intended structure.
This feature was requested and defined at:
[Fix Index Corruption](https://github.com/metacpan/metacpan-api/issues/1048)
as a result of the blocking incident documented at:
[MetaCPAN API - Indexing failed](https://github.com/metacpan/metacpan-docker/issues/47)
It introduces some of the same functionality like:
[Clear Unknown Indices](https://github.com/metacpan/metacpan-api/pull/1065)
which is required to create …
=> Verify Indices Mappings

lib/MetaCPAN/Role/Script.pm, lib/MetaCPAN/Script/Mapping.pm, lib/MetaCPAN/Script/Runner.pm, t/lib/MetaCPAN/TestServer.pm, t/script/mapping.t
This implements the `--delete --all` functionality discussed at:
[Fix Corrupted Indices](https://github.com/metacpan/metacpan-api/issues/1048)
which is needed to close definitely the issue of Index Corruption
[Unexpected Index Corruption](https://github.com/metacpan/metacpan-docker/issues/47)
by
1) Preventing the Index Corruption
2) Recovering from Index Corruption with "_Clear All Indices_" option
Additionally it implements Exit with Error Code for unconfirmed Operations
as mentioned at:
[ElasticSearch Availabilty Check](https://github.com/metacpan/metacpan-api/pull/1045)
This is also part of the logic to **prevent** accidental Indices Corruption
To test the functionality it introduces several Mapping Script Tests.
These tests are required to check the "_Verify Mappings_" functionality …
=> Clear Unknown Indices

t/lib/MetaCPAN/TestServer.pm
Messages that were the key to understand errors in the serverless automated _CircleCI_ test environment from the development at:
[Clear unknown Indices](https://github.com/metacpan/metacpan-api/pull/1065)
are no longer needed and can be cleared out
=> Clear out Messages in Tests

.github/workflows/update-snapshot.yml
- Bump CI Ubuntu from 20.04 to 22.04
- Use perl-actions/install-with-cpm for GH action install
=> Fix GH dep update workflow

lib/MetaCPAN/Document/CVE/Set.pm, lib/MetaCPAN/Query/CVE.pm, lib/MetaCPAN/Script/CVE.pm, lib/MetaCPAN/Script/Mapping/CVE.pm, lib/MetaCPAN/Server/Controller/CVE.pm
The `distribution`, `versions`, and `releases` fields need to be set to `"not_analyzed"` so they are matched exactly rather than as full text searches. This fixes #1103.
The `releases` field should be have `"$author/$release"`, not just `"$release"`. Together, they uniquely identify a release.
Returning an empty array is generally more friendly than returning a not found or empty result.
=> Fixes to CVE data and end points

lib/MetaCPAN/Script/CVE.pm
this fixes the warnings: "Argument "1.38_03" isn't numeric in numeric comparison (<=>)"
=> fix numeric sort

lib/MetaCPAN/Query/Release.pm
Some internal values are incorrect due to lack of defaults. This caused 'page_size' not to work when not combined with 'page'
=> release/recent: fix warnings + page_size

lib/MetaCPAN/Server/Controller/Release.pm
This reverts commit 7ae412956ee7acecf5203c9149508cc0daa10053.
This change is not working properly - the params are now received in the wrong order.
Need to check why the names of the params in the URL are reversed (page and size) when read inside the handler.
=> Revert "Bug fix: fix param order (GH#1126)"

lib/MetaCPAN/Server/Controller/Release.pm
This reverts commit 781f2141c08ccdb25e7ddc29a34940df9a3e0074.
The front end had been supplying the parameters incorrectly, and the API was accepting them incorrectly. So the front end was displaying correctly, but the API was incorrect. Fixing the API broke the pagination, which led to the original revert. The front end has now been fixed, so the API fix needs to be re-applied.
=> Revert "Revert "Bug fix: fix param order (GH#1126)""

.hadolint.yaml, Dockerfile
hadolint complains about installing apt packages without specifying a version. For rsync, this is exceedingly unlikely to be a problem, but still in spirit it makes sense to be more explicit. Specifying the version explicitly has caused problems several times because our base image has changed, and the given versions are no longer available.
Instead of specifying an exact package, we can use apt-get satisfy, which accepts a version string that can specify a minimum version.
I'm not sure if hadolint understands apt-get satisfy, but this stops it from complaining. And it already wasn't complaining about not specifying jq's version.
Also move the ignore rule about using a latest tag to an inline comment rather than in a separate file. This means it explicitly only covers the metacpan-base …
=> fix installing rsync by specifying a minimum rather than exact version

lib/MetaCPAN/Role/Script.pm, lib/MetaCPAN/Server.pm
The number of purges at Fastly seems very large. Logging the purges should help track down why.
=> log CDN purges

lib/MetaCPAN/Script/Author.pm, lib/MetaCPAN/Util.pm
Rewrite the author update script to only purge when we actually update an author.
=> rewrite author update script to only purge on updates

lib/MetaCPAN/Script/Author.pm, lib/MetaCPAN/Util.pm
Fixes some issues introduced by my recent author indexing changes.
We need to limit out scroll search to only the author type or it gives us every document and takes forever (even if skipping the other documents).
Also we need to allow extra fields at the top level of the structure when comparing, because some fields can be added by the front end. And since we won't overwrite them, they should be ignored when comparing.
Adds some logging about author differences, since we shouldn't ever have to update all that many authors. Log the difference we found for every 10th change found.
=> fix author indexing

lib/MetaCPAN/Script/Author.pm
When reading 00whois.xml, there can be cpanid elements containing duplicate id element values. This can happen when there is both a list and author entry for the same name. In these cases, the author entry is extraneous.
Rather than relying on XML::Simple's built in array to hash transformation (using id values), do the work ourselves so we can handle the duplicate id entries. Also configure XML::Simple to be more strict about how it parses.
=> author import: handle duplicate ids

.circleci/config.yml
This decreases build time from 20 minutes to 14 minutes. We're not even close to our maximum build minutes for April and we have been running a lot of builds this week, so we should be safe with this setting.
=> Switch CircleCI resource class from medium to large

lib/MetaCPAN/Server/QuerySanitizer.pm, t/server/sanitize_query.t
We no longer need metacpan_script for anything our code uses, and supporting it complicates our query filtering and interactions with Elasticsearch.
We've generally been trying to move away from users interacting via Elasticsearch queries, but if they really need to and need a specific script, they are always welcome to submit a PR to the API adding what they need.
=> drop support for metacpan_script

docs/API-docs.md, lib/MetaCPAN/Server/Controller.pm, lib/MetaCPAN/Server/Controller/Author.pm, lib/MetaCPAN/Server/Controller/Changes.pm, lib/MetaCPAN/Server/Controller/File.pm, lib/MetaCPAN/Server/Controller/Release.pm, t/server/controller/author.t
The join feature is something we try to add on top of Elasticsearch. It complicates our interactions with external queries and we don't use them anywhere in our own code.
=> remove join parameter

lib/MetaCPAN/Model/Search.pm
The 'expression' language is faster, more secure, and supported on modern versions of Elasticsearch. It requires numeric fields. Now that we have the numeric `documentation_length` field, we can use it to prefer shorter names rather than needing to put files onto the ES servers.
=> use inline expression script for preferring short module names

t/document/file.t
The pod_lines builder also sets slop. And the slop builder also sets pod_lines. Add a test that calls slop first, to ensure its builder works correctly.
=> test calling slop without calling pod_lines

lib/MetaCPAN/Server/Controller/Rating.pm, lib/MetaCPAN/Server/Controller/Scroll.pm, t/server/controller/rating.t
MetaCPAN::Client still expects this to work, so provide some fake results.
=> provide scrolled search for ratings with a fake id

lib/MetaCPAN/Server/Controller/Rating.pm, t/server/controller/rating.t
The fake rating search end points need the Deserialize ActionClass to parse their body.
Also, MetaCPAN::Client has a bug that prevents it from properly using its testing user agent, so just give the results for normal MC::C UAs.
=> fix parsing of rating end points

codecov.yml
Our tests are somewhat inconsistent in their coverage, so coverage can go down slightly even with unrelated changes. We also have untested code, and small tweaks will often be shown as a reduction in coverage.
Setting a 1% threshold will reduce friction on both of these cases. Any larger changes will still require an increase in coverage, so we should still trend upward over time.
=> set a 1% theshold for coverage changes

lib/MetaCPAN/Server/Controller/OAuth2.pm
tr takes a character class. Trying to give it a class wrapped in brackets will try to convert the bracket characters. We're just generating a random ID, so it's ok for the format being generated to change.
=> fix code generation in oauth2 controller

lib/MetaCPAN/Server/Controller/CVE.pm, lib/MetaCPAN/Server/Controller/Contributor.pm, lib/MetaCPAN/Server/Controller/Cover.pm, lib/MetaCPAN/Util.pm
tr/// always transforms character classes. Trying to put a regex character class wrapped in brackets will result in the brackets getting transformed, and other characters getting converted incorrectly.
Fix the tr/// used to generate a digest for an ID. This is only used for the contributors data, which is generally only updated when new releases are indexed. When querying the data, the author and release names are used, not the ID. The old records will continue to be found. If the data is reindexed, an additional record may be created for a release, but it should have the same data.
After making this change, eventually all of the contributor data should be recalculated to make sure the IDs are correct, and the old records purged. But they shouldn't interfere with anything until that is …
=> fix digest calculation from misuse or tr

cpanfile
So MetaCPAN understands packages that are `class`es
=> Increase version of Module::Metadata

.circleci/config.yml
This PR:
* reduces the CircleCI build time by ~10%
* simplifies the CircleCI config by using an official Orb rather than deprecated code
=> A large CircleCI VM can able to handle 4 test jobs

.circleci/config.yml
The oalders/cloud-config branch has been merged and deleted.
=> use primary branch in metacpan-docker when testing

lib/MetaCPAN/Script/Author.pm, lib/MetaCPAN/Script/Backup.pm, lib/MetaCPAN/Script/CPANTesters.pm, lib/MetaCPAN/Script/CPANTestersAPI.pm, lib/MetaCPAN/Script/Favorite.pm, lib/MetaCPAN/Script/Latest.pm, lib/MetaCPAN/Script/Mapping.pm, lib/MetaCPAN/Script/Suggest.pm, lib/MetaCPAN/Script/Watcher.pm
search_type: scan has been removed from newer Elasticsearch versions,
replaced with sort: _doc.
=> remove use of search_type scan

lib/MetaCPAN/Server/Controller.pm, lib/MetaCPAN/Server/Controller/Login.pm, lib/MetaCPAN/Server/Controller/Login/GitHub.pm, lib/MetaCPAN/Server/Controller/Login/Google.pm, lib/MetaCPAN/Server/Controller/Login/PAUSE.pm, lib/MetaCPAN/Server/Controller/Login/Twitter.pm, lib/MetaCPAN/Server/Controller/Pod.pm, lib/MetaCPAN/Server/Controller/Root.pm, lib/MetaCPAN/Server/Controller/User.pm
Controller actions without an explicit Arg/Args are treated as having infinite arguments. Add an Args(0) to the routes that are not expected to have sub-paths.
=> add Args(0) to controller actions not expected to recieve args

lib/MetaCPAN/Script/Latest.pm, lib/MetaCPAN/Script/Runner.pm
We don't need to handle the modules in any particular order, so using `_doc` sorting for better performance.
=> Fix performance of latest script

bin/cron/author.sh, bin/cron/backups.sh, lib/MetaCPAN/Model.pm, lib/MetaCPAN/Role/Script.pm, lib/MetaCPAN/Script/Backup.pm, lib/MetaCPAN/Types/TypeTiny.pm
The index option is meant to control the index that has all of our ES data. But in the future, each document type will need to be in a separate index. So the idea of having a global configurable index doesn't make sense.
The backup script needs to be able to operate on all indexes, and works generically with any type. Reimplement an index option for it, allowing multiple indexes to be specified.
=> remove index option from scripts and reimplement it for backup

lib/MetaCPAN/Types/TypeTiny.pm
Using command line options, the index option will always be assigned as an arrayref. But the default was still a plain string, which would error if no index option was given. The default could be changed to an array ref, but it also makes sense to coerce a normal string.
=> allow strings for backup script index option

lib/MetaCPAN/Script/CVE.pm
The old URLs have stopped working.
I'm not certain that the new URLs are the correct ones, but they seem to be getting updated regularly.
@stigtsp
=> update CVE data urls

app.psgi, cpanfile, cpanfile.snapshot, lib/MetaCPAN/API/Plugin/Model.pm, lib/MetaCPAN/Query/Search.pm, lib/MetaCPAN/Role/HasConfig.pm, lib/MetaCPAN/Role/Script.pm, lib/MetaCPAN/Server.pm, lib/MetaCPAN/Server/Config.pm, lib/MetaCPAN/Server/Model/Search.pm, lib/MetaCPAN/Util.pm, t/lib/MetaCPAN/TestHelpers.pm, t/model/search.t, t/script/cover.t, t/script/river.t, xt/search_web.t
Remove some unused prereqs.
Simplify the /v1/ URL handling in dev mode by using a mount, rather than a rewrite.
Move the search module to a query module, since it essentially matches the pattern of those modules.
Calculate the root directory based on the files, not based on git.
=> various cleanups

lib/MetaCPAN/Script/Snapshot.pm, metacpan_server.yaml, metacpan_server_testing.yaml, t/lib/MetaCPAN/Server/Test.pm, t/lib/MetaCPAN/TestServer.pm
Make all uses of elasticsearch_servers consistent, passing the value directly to the MooseX::Types::ElasticSearch::ES type coercion. This ensures we can use any value that the type will accept. This allows adding additional parameters that will be passed to the constructor.
With that allowed, explicitly set the client version we want to use. Since we are currently pinned to Search::Elasticsearch 2.03, this won't have any direct impact. But it will assist in upgrading the Search::Elasticsearch version.
A _local config with just a string specified will override the entire config, which for now will continue to work fine. Eventually, those should be updated to use a hash so they can override only the nodes.
=> Always use type coercion to construct Search::Elasticsearch object

cpanfile, cpanfile.snapshot, t/query/release.t
To support newer Elasticsearch versions, we want a new Search::Elasticsearch version. It still supports older versions, as long as the correct module is installed and it is instructed to use it.
We've already made the necessary changes to explicitly configure it to use Search::Elasticsearch::Client::2_0::Direct, so we are now free to upgrade.
=> update Search::Elasticsearch to latest

lib/MetaCPAN/Query/Release.pm
The perl dist isn't the only one with more than 250 releases.
=> return more versions for all dists

es/contributor/mapping.json, lib/MetaCPAN/Document/Contributor.pm, lib/MetaCPAN/Query/Contributor.pm, lib/MetaCPAN/Script/Contributor.pm, lib/MetaCPAN/Script/Release.pm, lib/MetaCPAN/Script/Role/Contributor.pm
All contributors, including those that can't be mapped to a PAUSE author, should be included in the contributor index. This will allow the web end points to look up all contributor information via the index, rather than needing to re-calculate for each call.
Adds the name and email fields to the contributor index, and populates them when calculating contributor data. The PAUSE id is no longer required, so it can't be used for the id of the ES doc. Instead, we delete all of the ids for a release before updating the data. Previously, the contributors script would ignore existing data. Now, it will delete and recreate the data.
For now, the release/contributors end point will still recalculate the data for each call. After this change is deployed and all of the data is updated, it can be …
=> include name and email in contributor index

lib/MetaCPAN/Script/Role/Contributor.pm
Allows the contributor script to keep running even if there is bad data in the release index (there is).
Cache the email to pause id mapping to speed up running across many releases.
=> make contributor script faster and more resilient

lib/MetaCPAN/Query/Release.pm
The contributors index now has all of the information needed for the /release/contributors index. We can use it rather than the more complicated calculation that was used to generate the index.
=> use contributors index for /release/contributors end point

lib/MetaCPAN/Model/Release.pm
package names extracted by PAUSE or Parse::PMFile are normalized to use double colons rather than apostrophe. Module::Metadata does not. Add the normalization to the output of Module::Metadata when we index files so that the module names will match what exists in 02packages.
=> normalize package names to use ::

lib/MetaCPAN/Document/File.pm
When checking if a file should be marked as indexed, if the documentation name (from the abstract) exists it is required to match the module name. The module name is normalized to use double colons rather than possibly apostrophes. Also normalize the documentation name when doing this comparison.
=> use normalized documentation name when comparing to module name

lib/Catalyst/Authentication/Store/Proxy.pm, lib/Catalyst/Plugin/Session/Store/ElasticSearch.pm, lib/MetaCPAN/API.pm, lib/MetaCPAN/Model/Archive.pm, lib/MetaCPAN/Model/Release.pm, lib/MetaCPAN/Query.pm, lib/MetaCPAN/Query/Role/Common.pm, lib/MetaCPAN/Role/Logger.pm, lib/MetaCPAN/Role/Script.pm, lib/MetaCPAN/Script/Release.pm, lib/MetaCPAN/Script/Snapshot.pm, lib/MetaCPAN/Server/Model/ES.pm, lib/MetaCPAN/Types/TypeTiny.pm, t/lib/MetaCPAN/Script/MockError.pm, t/lib/MetaCPAN/Server/Test.pm, t/lib/MetaCPAN/Tests/Extra.pm, t/lib/MetaCPAN/Tests/Model.pm, t/model/release.t, t/model/release/dependencies.t, t/model/release/metadata.t
The types in the document classes are not changed, as they should be going away soon.
=> Use Type::Tiny based types in most cases

lib/MetaCPAN/Document/Module.pm
When searching for a package line to see if it is intentionally hidden, we are matching against the specific module that we are using. But the name that exists in the code could include apostrophes instead of double colons, while the recorded module name is normalized to use colons.
Construct a regex to allow matching the module name but with apostrophe package separators.
=> when searching for a package line, allow apostrophes in the module name

lib/MetaCPAN/Script/Mirrors.pm
The mirror network is gone, but we still index the list of the one mirror. While we could consider removing this index in the future, for now just fix the script to use Elasticsearch directly rather than ElasticSearchX::Model.
=> rewrite mirror script to avoid ESXM

.gitignore, lib/MetaCPAN/Server.pm, lib/MetaCPAN/Server/Config.pm, metacpan_server_testing.yaml
This ensures that the configuration used by Catalyst is the same as what is used by the scripts and everything else. And it allows a `metacpan_server_testing_local` config file to be used.
=> Improved configuration mechanism for testing

lib/MetaCPAN/Query/File.pm
This was broken by a29eff9fbe01a93a711e92f5554228e4c0186a23.
Fixes metacpan/metacpan-web#3309
=> fix autocomplete not including exact matches

lib/MetaCPAN/Query/File.pm
For https://github.com/metacpan/metacpan-web/issues/3246 - _doc_files will handle all-caps, md and pod variants of the files, `security.txt` included separately. Not sure if this is enough to include them in "other files" on the release page.
=> Add "security" category for special files

lib/MetaCPAN/Document/File.pm, lib/MetaCPAN/Document/Module.pm, lib/MetaCPAN/Model/Release.pm, lib/MetaCPAN/Util.pm, t/document/file.t, t/document/module.t, t/lib/MetaCPAN/Tests/Release.pm, t/release/file-duplicates.t
Module::Metadata and Parse::PMFile will already exclude modules using the 'hide from PAUSE' trick. There is no need to add an additional check on top of that.
=> remove special check for hidden packages

lib/MetaCPAN/Query/File.pm, lib/MetaCPAN/Server/Controller/Pod.pm, lib/MetaCPAN/Server/Model/Source.pm
The find_pod method would sometimes return the source and sometimes a full record from Elasticsearch. Fix the return to always return the source, and adjust the caller to work with this form.
=> fix the pod end point when given a module name
