metacpan/metacpan-api

- .travis.yml
- cpanfile
- cpanfile.snapshot
- lib/Catalyst/Plugin/Session/Store/ElasticSearch.pm
- lib/MetaCPAN/Document/File.pm
- lib/MetaCPAN/Document/Release.pm
- lib/MetaCPAN/Role/Script.pm
- lib/MetaCPAN/Script/Latest.pm
- lib/MetaCPAN/Server/Controller.pm
- lib/MetaCPAN/Server/Controller/Scroll.pm
- lib/Plack/Session/Store/ElasticSearch.pm
- t/fakecpan.t
- t/release/documentation-not-readme.t
- t/release/meta-provides.t
- t/release/pod-examples.t
- t/server/controller/author.t
- t/server/controller/module.t
- t/server/controller/search/autocomplete.t
- t/server/controller/search/reverse_dependencies.t
- t/server/sanitize_query.t
> Revert "[WIP]Elasticsearch Upgrade"

- lib/MetaCPAN/Document/Release.pm
- lib/MetaCPAN/Model/Release.pm
- t/release/badpod.t
- t/release/binary-data.t
- t/release/documentation-hide.t
- t/release/documentation-not-readme.t
- t/release/file-changes.t
- t/release/file-duplicates.t
- t/release/local-lib.t
- t/release/meta-license.t
- t/release/meta-provides.t
- t/release/moose.t
- t/release/multiple-modules.t
- t/release/oops-locallib.t
- t/release/packages-unclaimable.t
- t/release/packages.t
- t/release/pod-examples.t
- t/release/pod-with-data-token.t
- t/release/pod-with-generator.t
- t/release/prefer-meta-json.t
- t/release/scripts.t
- t/release/some-trial.t
This is a pull request for #149 , but it's still in progress. I also need to add a test.
*requires new mappings*
> add main_module attribute (adds new mappings)

- lib/MetaCPAN/Server/Controller/Pod.pm
This should fix CPAN-API/metacpan-web#1561
> Double the allowed size of POD documents

- lib/MetaCPAN/Script/Tickets.pm
- t/release/text-tabs-wrap.t
- t/var/fakecpan/bugs.tsv
- t/var/fakecpan/configs/text-tabs+wrap-2013.0523.yml
refs CPAN-API/metacpan-web#1577
> URI-escape rt bugs source url

- lib/MetaCPAN/Script/River.pm
This addresses recent details in #460
> Accept gzipped river data

- lib/MetaCPAN/Script/Backup.pm
this will make the author data import work
> fix backup script (use update when id exists)

- cpanfile
- cpanfile.snapshot
- lib/MetaCPAN/Script/Mapping.pm
> prompt for confirmation on mapping --delete

- cpanfile
- t/model/archive.t
hopefully make the test pass on 5.22 on travis :)
> t/model/archive: replace size check with content check

- lib/MetaCPAN/Script/Release.pm
support `--queue` flag in `release` script, to allow it to queue its jobs.
it will allow speeding up crons like:
`... bin/metacpan release --skip --age 25 --detect_backpan --latest `
by sending all their jobs to the minion queue using:
`... bin/metacpan release --queue --skip --age 25 --detect_backpan --latest `
> Support queueing from Script::Release

- lib/MetaCPAN/Script/Latest.pm
it's required for some manual checks.
> script/latest: support 'force update'

- lib/MetaCPAN/Document/File/Set.pm
- lib/MetaCPAN/Server/Controller/Source.pm
This is an improvement over my last attempt of providing in-dist links for non-indexed or non-latest pod.
> improve link choices for in-dist modules/pod

- lib/MetaCPAN/Script/Release.pm
add --latest when using --queue
> when queueing from script/release also provide --latest

- lib/MetaCPAN/Pod/Renderer.pm
- lib/MetaCPAN/Server/Controller/Pod.pm
- lib/MetaCPAN/Server/Controller/Source.pm
- lib/MetaCPAN/Server/View/Pod.pm
This allows an alternate URL prefix to be used when rendering Pod.
> Add url_prefix option to pod endpoint

- lib/MetaCPAN/Document/File/Set.pm
> fix download_url version filtering notation parsing (!=, <=, etc.)

- t/server/controller/download_url.t
per #519 
added validation for the download_url response + the various version notation options.
> added tests for download_url controller

- lib/MetaCPAN/Server/Controller.pm
for #522 
not sure if that's a complete solution, but it works for me.
> fix 'source' parameter for request body

- t/server/controller/url_parameters.pm
#524 
created a generic test file for URL parameters, in case we have more to add tests for.
> add test for the URL parameters: test 'source'

- lib/MetaCPAN/Script/Release.pm
in the case we are using `--queue` & `--latest` in sctipt/release - queue the 'latest' jobs in lower priority instead of executing script from within a script
> queue 'latest' jobs from 'release' (if queue is used)

- .travis.yml
Attempt to install all requirements with specific versions outlined in
cpanfile.snapshot, and versions outlined in cpanfile
[Travis-CI cron jobs](https://docs.travis-ci.com/user/cron-jobs) look easy to setup. They do not appear to be controlled via .travis.yml, and can work on a specific branch.
> New build matrix

- lib/MetaCPAN/Server/Controller/Search/Autocomplete.pm
> only include listed fields in autocomplete output

- docs/indexing.md
- t/tidyall.t
@tsibley - can we merge this :) ?
> Notes on digging into the authorized and indexed flags

- lib/MetaCPAN/Script/Mapping.pm
make `type` copying a bit more automatic.
> default type copy to monthly slices (unless query is provided)

- cpanfile
- cpanfile.snapshot
- lib/MetaCPAN/Document/File.pm
- lib/MetaCPAN/Document/File/Set.pm
- lib/MetaCPAN/Script/Mapping.pm
- lib/MetaCPAN/Script/Mapping/CPAN/Author.pm
- lib/MetaCPAN/Script/Mapping/CPAN/Distribution.pm
- lib/MetaCPAN/Script/Mapping/CPAN/Favorite.pm
- lib/MetaCPAN/Script/Mapping/CPAN/File.pm
- lib/MetaCPAN/Script/Mapping/CPAN/Mirror.pm
- lib/MetaCPAN/Script/Mapping/CPAN/Rating.pm
- lib/MetaCPAN/Script/Mapping/CPAN/Release.pm
- lib/MetaCPAN/Script/Mapping/User/Account.pm
- lib/MetaCPAN/Script/Mapping/User/Identity.pm
- lib/MetaCPAN/Script/Release.pm
- lib/MetaCPAN/Server/Controller/Search/Autocomplete.pm
An amendment to #599 ... all the changes that were lost in squashing + rebasing.
The `suggest` field here doesn't work yet (therefore WIP), needs review.
> [WIP] autocomplete suggester

- lib/MetaCPAN/Script/Snapshot.pm
You can:
- setup
- snap
- list
- restore
Built so that it's easy to put quite complex configs into cron
> Script for ES Snapshots

- lib/MetaCPAN/Document/File/Set.pm
sorting by length in the query to correct current results set.
> autocomplete_using_suggester: improve sorting by length

- lib/MetaCPAN/Script/Suggest.pm
small change that was required while running the 'all' (backfilling for all files) - month resolution is not high enough (times out)
> script/suggest: support day resolution slices for 'all'

- lib/MetaCPAN/Document/File.pm
- lib/MetaCPAN/Document/Release.pm
- lib/MetaCPAN/Model/Search.pm
- lib/MetaCPAN/Script/Watcher.pm
- lib/MetaCPAN/Server/Controller/Changes.pm
a couple of code cleanups & simplified queries.
> api cleanups

- lib/MetaCPAN/Document/Release.pm
- lib/MetaCPAN/Model/Search.pm
- lib/MetaCPAN/Server/Controller/Changes.pm
This reverts commit cd7d99878eb343e02c374f13be938d5c4e202c74.
This may be causing some issues - to be investigated.
> Revert "simplify multi-value term queries (using 'terms')"

- lib/MetaCPAN/Document/Release.pm
- lib/MetaCPAN/Server/Controller/Release.pm
This query is currently being generated in JS in the WEB.
This commit moves it to the API and introduces a new endpoint
to serve the data.
> Moved the contributors querying to a new API endpoint

- lib/MetaCPAN/Document/Package.pm
- lib/MetaCPAN/Server/Controller/Package.pm
- t/server/controller/package.t
This new endpoint will be used for the new perms page
> Added a /package/modules/DIST endpoint

- lib/MetaCPAN/Document/Release.pm
- lib/MetaCPAN/Server/Controller/Release.pm
This endpoint /release/files/RELEASE?files=FILE1,FILE2,...
will lookup whether the release has files corresponding to
the given file names and will return the names & paths for
the found files.
> Added an endpoint for looking up files for a release

- lib/MetaCPAN/Server/Controller.pm
> Bug fix: don't explode on non-existing types (GH#576)

- lib/MetaCPAN/Script/Mapping.pm
Will allow introducing new indices more easily.
> Simplify the mapping deploy method

- lib/MetaCPAN/Script/Contributor.pm
added the flag: --age N to update releases with value of
the 'date' field in the last N days.
added debug level logging of release names.
> script/contributor: added flag 'age' + debug logging

- lib/MetaCPAN/Document/Favorite.pm
- lib/MetaCPAN/Server/Controller/Favorite.pm
This endpoint will replace the query in WEB that is used
in several places, and will simplify the code using it.
> Added /favorite/by_user/USER endpoint

- lib/MetaCPAN/Document/Author.pm
- lib/MetaCPAN/Server/Controller/Author.pm
This endpoint will replace an Elasticsearch query in WEB.
> Added /author/by_user/USER endpoint

- lib/MetaCPAN/Document/Release.pm
- lib/MetaCPAN/Server/Controller/Activity.pm
This new endpoint will replace the query currently generated and
sent from WEB.
> Added Activity controller + /activity endpoint

- lib/MetaCPAN/Script/Role/External/Debian.pm
- lib/MetaCPAN/Script/Role/External/Fedora.pm
to fix error mentioned in #670 
just going to go ahead and merge this - will create the tests next.
> external scripts: resolve sub name conflict

- lib/MetaCPAN/Document/Favorite.pm
- lib/MetaCPAN/Server/Controller/Favorite.pm
This endpoint will replace the query sent from WEB.
> Added /favorite/recent endpoint

- lib/MetaCPAN/Document/File/Set.pm
- lib/MetaCPAN/Server/Controller/File.pm
> Added /dir/PATH endpoint

- lib/MetaCPAN/Document/Release.pm
- lib/MetaCPAN/Server/Controller/Release.pm
> Added /release/all_by_author/PAUSEID endpoint

- README.md
- bin/build_test_CPAN_dir.pl
- lib/MetaCPAN/Script/River.pm
- lib/MetaCPAN/Script/Tickets.pm
> update links to old API

- lib/MetaCPAN/Document/Favorite.pm
- lib/MetaCPAN/Server/Controller/Favorite.pm
> Added /favorite/leaderboard API endpoint

- lib/MetaCPAN/Document/Release.pm
- lib/MetaCPAN/Server/Controller/Release.pm
> Added /release/versions/DIST endpoint

- lib/MetaCPAN/Document/Permission.pm
- lib/MetaCPAN/Server/Controller/Permission.pm
/permission/by_author/PAUSEID
/permission/by_module/MODULE
/permission/by_module?module=MODULE1&module=MODULE2...
These endpoints will be used to replace the queries being sent
from WEB.
> Added new permission API endpoints

- lib/MetaCPAN/Document/Release.pm
- lib/MetaCPAN/Server/Controller/Release.pm
> Added /release/top_uploaders API endpoint

- lib/MetaCPAN/Document/Favorite.pm
- lib/MetaCPAN/Server/Controller/Favorite.pm
The new endpoint will be used to replace the query being sent
from WEB.
> Added /favorite/users_by_distribution/DISTRIBUTION API endpoint

- lib/MetaCPAN/Document/Author.pm
- lib/MetaCPAN/Server/Controller/Author.pm
This endpoint will be used to replace the query being sent
from WEB.
> Added /author/search?q=QUERY API endpoint

- lib/MetaCPAN/Document/File/Set.pm
- lib/MetaCPAN/Server/Controller/Release.pm
This endpoint will be used to replace the query being sent
from WEB.
> Added /release/interesting_files/PAUSEID/RELEASE

- lib/MetaCPAN/Document/Release.pm
These values will simplify adoption by WEB
> Added 'total' & 'took' values to the /release/versions endpoint

- lib/MetaCPAN/Document/File/Set.pm
These values will simplify adoption by WEB
> Added 'total' & 'took' to /release/interesting_files endpoint

- lib/MetaCPAN/Document/Release.pm
- lib/MetaCPAN/Server/Controller/Release.pm
This endpoint will replace the query sent from WEB.
> Added new /release/modules/PAUSEID/RELNAME endpoint

- lib/MetaCPAN/Document/Release.pm
- lib/MetaCPAN/Server/Controller/Release.pm
This PR contains 2 separate commits for 2 new endpoints which share the same calling code on WEB and will need to be deployed together - therefore are bound together here.
> release new endpoints

- lib/MetaCPAN/Document/Release.pm
- lib/MetaCPAN/Server/Controller/Release.pm
This endpoint will replace query sending from WEB
> Added /release/by_author/PAUSEID endpoint

- lib/MetaCPAN/Document/Favorite.pm
- lib/MetaCPAN/Server/Controller/Favorite.pm
This new endpoint will replace query sending from WEB.
> Added /favorite/agg_by_distirbutions API endpoint

- lib/MetaCPAN/Document/Mirror.pm
- lib/MetaCPAN/Server/Controller/Mirror.pm
- t/server/controller/mirror.t
This endpoint will replace query sending from WEB
> Added /mirror/search API endpoint

- lib/MetaCPAN/Document/Rating.pm
- lib/MetaCPAN/Server/Controller/Rating.pm
This endpoint will replace query sending from WEB
> Added /rating/by_distributions API endpoint

- lib/MetaCPAN/Document/Author.pm
- lib/MetaCPAN/Server/Controller/Author.pm
This endpoint will replace query sending from WEB.
> Added /author/by_ids endpoint

- lib/MetaCPAN/Script/Role/External/Fedora.pm
stop the annoying emails... will merge as soon as tests are done
> script/external/fedora: print --> log_debug

- lib/MetaCPAN/Document/File/Set.pm
- lib/MetaCPAN/Server/Controller/Search/DownloadURL.pm
Keep the controller code concise and unaware of the data structure.
> Controller/DownloadURL - move data handling to Document module

- lib/MetaCPAN/Document/File/Set.pm
- lib/MetaCPAN/Server/Controller/Search/Autocomplete.pm
Keep the controller code concise and unaware of the data structure.
> Controller/Autocomplete - move data handling to Document module

- lib/MetaCPAN/Server/Controller/Author.pm
> /author/by_user: accept POST params

- lib/MetaCPAN/Server.pm
- lib/MetaCPAN/Server/Controller/Author.pm
- lib/MetaCPAN/Server/Controller/Favorite.pm
- lib/MetaCPAN/Server/Controller/Permission.pm
- lib/MetaCPAN/Server/Controller/Rating.pm
With a growing use of the same pattern of reading parameters
from either the URL or the body, this method allows reuse and
simplification of the route handlers code.
> Added controller method for improving/simplifying param reading

- .travis.yml
- cpanfile
- cpanfile.snapshot
- lib/MetaCPAN/Model/Search.pm
- t/model/search.t
- xt/README.txt
- xt/search_web.t
This is mostly just renaming variables that were confusing and adding some pod here and there. There isn't any change to actual queries.
> Leo/search refactor 2.0 - a cleanup

- .gitignore
- app.psgi
- cpanfile
- cpanfile.snapshot
- lib/MetaCPAN/Server.pm
- lib/MetaCPAN/Server/Controller/User.pm
- log4perl.conf
- t/model/search.t
- t/server/controller/release.t
- xt/search_web.t
The scripts use their own configuration for now, although preferrably we
will merge them together.
> add log4perl logging to server web app

- lib/MetaCPAN/Document/File/Set.pm
This supports @tsibley 's usage of autocomplete elsewhere. It will need a corresponding change in metacpan-web
> return structured data from suggest endpoint

- README.md
before
after
Thank you all for meta::hack v2!
> change badge (png -> svg) and add kritika badge

- lib/MetaCPAN/Queue.pm
- lib/MetaCPAN/Script/Favorite.pm
- lib/MetaCPAN/Script/Mapping/CPAN/File.pm
- t/00_setup.t
- t/lib/MetaCPAN/TestServer.pm
This script will be used to fill dist_fav_count in 'file' type
(to boost search abilities)
The script supports queueing for parallel distribution handling.
> Added a Favorite script

- lib/MetaCPAN/Document/File/Set.pm
- lib/MetaCPAN/Server/Controller/Pod.pm
The querying doesn't need to be in the controller.
This will also ease future refactoring.
> Run query from document set, not thhe controller

- lib/MetaCPAN/Script/CPANTestersAPI.pm
Api-2 is also frequently down, so I've created api-3. Eventually, I'll actually whack the mole...
> use working cpan testers api server

- lib/MetaCPAN/Script/CPANTestersAPI.pm
Can we please make that script less noisy?
> less noise from script

- lib/MetaCPAN/Model/Search.pm
This will hopefully fix the issue of sometimes badly ordered
results in search.
> Change queries to use search type 'dfs_query_then_fetch'

- docs/API-docs.md
Some developers that may use this API may not be familiar with terms like API and DSL, or even why you would care about an API.
> Minor changes to make the API docs more accessible

- lib/MetaCPAN/Document/Author.pm
- lib/MetaCPAN/Model/User/Account.pm
- lib/MetaCPAN/Server/Controller/User.pm
> clear author's user when disconnecting from PAUSE

- lib/MetaCPAN/Script/Latest.pm
- lib/MetaCPAN/Script/Mapping.pm
- lib/MetaCPAN/Script/Session.pm
Bug fix for Script::Mapping and a few code updates, mainly to help with debugging of Script::Latest
> scripts updates

- lib/MetaCPAN/Script/Release.pm
> Ensure provides is unique

- t/model/search.t
now /search/web doesn't strip {hits}
> Fix /search/web test

- lib/MetaCPAN/API.pm
Use the configuration dsn to determine whether Minion should use
PostgreSQL or SQLite, allowing developer choice for their database
backend.
> Add support for sqlite database with Minion

- cpanfile
- cpanfile.snapshot
- lib/MetaCPAN/API.pm
This merge request bumps the version of `Mojolicious::Plugin::MountPSGI` that enables setting of `PLACK_ENV`.
> Update MountPSGI to set PLACK_ENV

- cpanfile
- cpanfile.snapshot
- lib/MetaCPAN/Model/Email/PAUSE.pm
- lib/MetaCPAN/Role/HasConfig.pm
- lib/MetaCPAN/Server/Controller/Login/PAUSE.pm
- lib/MetaCPAN/Util.pm
- metacpan_server.conf
- metacpan_server_testing.conf
- t/model/email/pause.t
- t/util.t
This relies on the credentials PR I just created getting merged first.
> Move email sending to a model class

- lib/MetaCPAN/Server.pm
We could later do this with a Mojo plugin but we won't be using it for the time being.
> remove server-status URL for now

- lib/MetaCPAN/Query/Release.pm
- lib/MetaCPAN/Server/Controller/ReverseDependencies.pm
> Fix size parameter reading for reverse_dependencies (GH#736)

- root/static/requests/cover.yml
Now that this code is working it's important to return the right
results.
> Add detailed response data for cover

- cpanfile
- cpanfile.snapshot
The build was failing.  This seems to help.  Still have many more deps to update, but we can get to those later.  I hope to automate this partially via GitHub workflows.
> Bump some config deps

- lib/MetaCPAN/Document/File/Set.pm
This is a PR of @mickeyn's work.  Fixes #945
> Add date to suggestions

- lib/MetaCPAN/Query/File.pm
https://metacpan.org/pod/Dist::Zilla::Plugin::PrereqsFile
> Show prereqs files on release page if present

- lib/MetaCPAN/Query/File.pm
The list of things we're trying to list for examples included 'ex' and
'examples'.  These don't both make sense to match in the same way.
Split the file and path matching. Match directories at the top level,
not just the path prefix. This prevents matching a /ext/ directory. And
match files starting with examples, but not ex.
> split examples into paths and files

- lib/MetaCPAN/Script/Author.pm
This will 
1. add single-pauseid handling flag to the author script
2. fix name update in case of custodial account
This will fix #621
> Author script updates

- lib/MetaCPAN/Document/Distribution.pm
> Distribution: add defulat river values for first release

- lib/MetaCPAN/Query/Release.pm
- t/model/release/reverse_dependencies.t
- t/query/release.t
> Fix reverse deps search exception

- cpanfile
- cpanfile.snapshot
Hopefully fixes metacpan/metacpan-web/issues/2694
> Bump Type::Tiny from 1.002005 to 1.016008

- cpanfile
- cpanfile.snapshot
- Bump Cpanel::JSON::XS from 4.29 to 4.32
- Bump JSON::MaybeXS from 1.003009 to 1.004004
> Update JSON deps

- cpanfile
- cpanfile.snapshot
Also bumps Exporter::Tiny from 1.000000 to 1.004004
> Bump Type::Tiny from 1.016008 to 2.000001

- .circleci/config.yml
> Use CircleCI's checkout step for this repo

- lib/MetaCPAN/Query/Release.pm
The reverse dependency query attempted to find releases with a dependency of a given name and a relationship of 'runtime'. But because the dependencies are stored as an array and it was not doing a nested query, it was actually searching for a release with a dependency of a given name, and any other dependency with a relationship of 'runtime'.
Fix this by using a nested query for the dependency array, and include an additional filter on the phase. We don't want to include reverse dependencies of "develop" or other custom phases.
> fix reverse dependency query

- lib/MetaCPAN/Server/Controller/Release.pm
> fix content type of /release/version?plain=1

- lib/MetaCPAN/Server/Controller/Release.pm
Fixes parameter order bug reported in #1126
> Bug fix: fix param order (GH#1126)

- lib/MetaCPAN/Query/Release.pm
- lib/MetaCPAN/Server/Controller/Release.pm
Adding a page parameter support for /release/by_author
solves #1129
> release/by_author: support 'page' parameter

- lib/MetaCPAN/Query/Release.pm
> /release/recent - added maturity field GH#1146

- lib/MetaCPAN/Query/Release.pm
This makes it match the fields returned by the author all releases end point.
> include additional fields in author latest releases query

- lib/MetaCPAN/Server/Controller/User/Favorite.pm
We should be purging the relevant tags when favorites are added or removed. Currently, the front end does this, but it really should be handled by the API server.
> purge from cdn on favorite changes

- lib/MetaCPAN/Script/Tickets.pm
Add proper error handling to the GitHub issue count code. If the repo is missing, we can assume it has been deleted, so we can delete the issue information we have stored. Other errors can get logged and investigated later.
> Handle errors more gracefully when updating GitHub issue counts

- lib/MetaCPAN/Script/Mapping/User/Account.pm
- lib/MetaCPAN/Script/Mapping/User/Session.pm
> remove unused _timestamp field from mappings

- lib/MetaCPAN/Query/Release.pm
Rather than trying to fill in each pause id on a separate query, run one query for all contributors. Significantly speeds up fetches for large contributor lists.
> contributors: fetch all contrib pauseids in one query

- lib/MetaCPAN/Query/Release.pm
- t/server/controller/author.t
See https://github.com/metacpan/metacpan-puppet/issues/253
> Drop backpan_directory from author api
